### ISSUE TITLE
Importer adds duplicate information

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/cedar#8]
Importer generates duplicate prefLabels and relation links
![screenshot from 2016-05-02 13 39 13](https://cloud.githubusercontent.com/assets/7347746/14963912/8f2ea264-106b-11e6-8d08-a5244e47433d.png)
![screenshot from 2016-05-02 13 39 52](https://cloud.githubusercontent.com/assets/7347746/14963916/95577f44-106b-11e6-8b86-af9ea175b230.png)

**Comment by seanlw** [comment]
I can't seem to replicate the issue, but if I could this is a problem with the Iqvoc gem which will have be be reported with them. This problem might also only exist in the way we are doing testing in the database. If this problem comes up again in production a ticket will be made with Iqvoc for a fix.
